#_ver=20140602_165943


readline(prompt="plot TpmC now?");
source('.rlib.parthenon.2014s1.tpmc_barplot.r');


# this requires '.rcmd.parthenon.2014s1.plot_tp10s.r'
# which is automatically generated by '.bdx.0214.y.parthenon.2014s1.exec__mk_rcmd__plot_tp10s.sh'
readline(prompt="plot tp10s now?");
source('.rcmd.parthenon.2014s1.plot_tp10s.r');


tp10s_dist_plot <- function(target_data, target_name, max_x, max_y) {
	text_y_offset = max_y / 50;
	this <- unlist(target_data); # this <- unlist(tp10s.ext4.L3_C020_1_of_5);
	this_summary <- summary(this);
	this_mean <- round(this_summary[4], digits=1);
	this_sd <- round(sd(this), digits=1);
	this_qu1 <- round(this_summary[2], digits=1); # 1st Quantile
	this_qu2 <- round(this_summary[3], digits=1); # Median
	this_qu3 <- round(this_summary[5], digits=1); # 3rd Quantile
	tpmc = this_mean * 6;

	plot(table(this), main=paste("Tp10s distribution - ", target_name, "( TpmC:", tpmc, ")"), sub=paste("average:", this_mean, " ,  stdev:", this_sd), xlab="tp10s", ylab="count", xlim=c(0, max_x), ylim=c(0, max_y));

	y_base_qu= max_y * 4/6;
	rect(xleft=this_qu1, xright=this_qu3, ybottom=0, ytop=y_base_qu, density=10, col='green', angle=45);
	abline(v=this_qu2, col='dark green');
#	abline(v=c(this_qu1, this_qu3), col='green');
	text(x=this_qu2, y=(y_base_qu + 10*text_y_offset), format(paste("median(", format(this_qu2), ")")), col='dark green');
	text(x=this_qu1, y=(y_base_qu + 5*text_y_offset), format(paste("1st Qu.(", format(this_qu1), ")")), col='dark green', pos=2);
	text(x=this_qu3, y=(y_base_qu + 5*text_y_offset), format(paste("3rd Qu.(", format(this_qu3), ")")), col='dark green', pos=4);

	y_base_mean = max_y * 2/6;
	rect(xleft=this_mean - this_sd, xright=this_mean + this_sd, ybottom=0, ytop=y_base_mean, density=10, col='orange', angle=45+90);
	abline(v=this_mean, col='red')
#	abline(v=c(this_mean - this_sd, this_mean + this_sd), col='orange')
	text(x=this_mean, y=(y_base_mean + 10*text_y_offset), format(paste("avg(", format(this_mean), ")")), col='red');
	text(x=this_mean - this_sd, y=(y_base_mean + 5*text_y_offset), format(paste("avg-sd(", format(this_mean-this_sd), ")")), col='red', pos=2);
	text(x=this_mean + this_sd, y=(y_base_mean + 5*text_y_offset), format(paste("avg+sd(", format(this_mean+this_sd), ")")), col='red', pos=4);

}


readline(prompt="plot tp10s_dist now?");


target_list <- ls(pattern="tp10s.*L3*", all.names=T);
tab_max = 0;
for (target in target_list) {
	tab_max <- max(tab_max, max(table(unlist(get(target)))));
}
max_tp10s = ymax;
for (target in target_list) {
	tp10s_dist_plot(target_data = get(target), target_name = target, max_x = max_tp10s, max_y = tab_max * 1.2);
}


